### ISSUE TITLE
Connect opencv with react native

### ISSUE THREAD

**Issue by ramipaleo** [wallabyway/rn-opencv-demo#1]
Hi Michel,

Do you have an example where you use the android camera with opencv on react native?

**Comment by ugiacoman** [comment]
This project looks like an awesome dream, but does it actually work? I don't see any references to opencv anywhere in the codebase...

**Comment by pgarciacamou** [comment]
@wallabyway was this project finished?

I'm looking for a RN-OpenCV module.

**Comment by DeveBj** [comment]
guys any leads regarding open cv usage with React Native

**Comment by peter-mach** [comment]
I personally need to do iOS/Android app that will take the photo when appropriate colored rectangle is detected in a viewport.  
Similar to this: https://www.youtube.com/watch?v=BG67VZFbvAw

Any help would be appreciated.

**Comment by pgarciacamou** [comment]
IMO looking at this repo and the respective forks, between all the commit history and the contributor's contributions, this repo seems to be no longer under development :/

@wallabyway would you be willing to transfer it to someone that might want to continue working on it?

**Comment by wallabyway** [comment]
Yes absolutely. I feel bad this wasn't completed.  (Under resourced)

What do you need me to do?

On Mar 13, 2017 10:43 AM, "Pablo Garcia" <notifications@github.com> wrote:

IMO looking at this repo and the respective forks, between all the commit
history and the contributor's contributions, this repo seems to be no
longer under development :/

@wallabyway <https://github.com/wallabyway> would you be willing to
transfer it to someone that might want to continue working on it?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/wallabyway/rn-opencv-demo/issues/1#issuecomment-286186094>,
or mute the thread

**Comment by ugiacoman** [comment]
Is opencv even something that should be done in a `js` thread at all?

**Comment by pgarciacamou** [comment]
@ugiacoman 

According to react-native documentation:

> With React Native, you don't build a “mobile web app”, an “HTML5 app”, or a “hybrid app”. You build a real mobile app that's indistinguishable from an app built using Objective-C or Java.

To my understanding, the app will be compiled to native code either way. In theory, there should not be any actual JS running in the device. **If this is true**, there should not be any difference between doing it in swift, objective-c or as you mention through "*a `js` thread*"

**Comment by ugiacoman** [comment]
@pgarciacamou React Native does not compile to native code. It acts as a bridge between native components (ie. `UIButton` on iOS) and `js`. On device there are two main threads. A `js` thread that runs and the native thread.

To make a react native component performant, you want to minimize the amount of transportation between the threads. Think of how a device handles gestures for an example.

More on performance: https://facebook.github.io/react-native/docs/performance.html

Imagine using the node `opencv` module instead of the `C` module. You'd be streaming the video from the native thread to the `js` thread and doing all the computations on the `js` thread. I do not know if this will affect performance or not.

**Comment by pgarciacamou** [comment]
@ugiacoman I see. Then, would it make difference to run any heavy computations on the native side and communicate the result through the thread?

**Comment by ugiacoman** [comment]
@pgarciacamou I think so, it'd be really cool to do a comparison, but I'd imagine the computations would be better handled in `C++`. I know java has an opencv (javaCV) library and with iOS you need to bridge to `obj-c` but it'll work. Maybe that could be our starting point: exposing the opencv API to react-native?

**Comment by pgarciacamou** [comment]
> Maybe we that could be our starting point: exposing the opencv API to react-native?

Exactly what I had in mind.

**Comment by ugiacoman** [comment]
@pgarciacamou Sweet, I have a lot of experience with iOS dev, and a little with android. Which would you rather focus on?

**Comment by pgarciacamou** [comment]
Well, I've been working with react-native for only around 2 months and all my exp is on HTML, CSS and JS.

That said, I don't really have time to fully focus on this. I could review and pitch in when needed.

@ugiacoman would you want @wallabyway to transfer this repo to you?

**Comment by ugiacoman** [comment]
@pgarciacamou @wallabyway Oh okay, yeah sure! I'd probably make it more general and stray from the pokemon but this is something that I would be actively developing in my spare time :)

**Comment by pgarciacamou** [comment]
@wallabyway could you follow these instructions to transfer the repo to @ugiacoman ?

https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/

thanks to both!

**Comment by wallabyway** [comment]
ok, transferred!

**Comment by ugiacoman** [comment]
thanks!

**Comment by hugohow** [comment]
Hi, how did you advance in this topic ? It seems promising, I will try to integrate it opencv in rn also

**Comment by ugiacoman** [comment]
@hugohow Unfortunately, I am working on other projects currently. I hope to come back to this soon! Exposing all the methods shouldn't be difficult, just time consuming :)

**Comment by DavitVosk** [comment]
@hugohow  @ugiacoman Guys, did you do anything with this module creation? Now I am working on the app where I need image quality improvement. And this module is nice to have one

**Comment by ugiacoman** [comment]
@DavitVosk Not yet!

**Comment by DavitVosk** [comment]
@ugiacoman I need some image quality increasing operations for Android. Do you know which module I can use now or how can I do this? Thanks in advance

**Comment by wallabyway** [comment]
@ugiacoman - what do you think about ARkit + react-native ?

https://techcrunch.com/2017/06/05/apple-enters-the-augmented-reality-fray-with-arkit-for-ios/

**Comment by DavitVosk** [comment]
@wallabyway I see that this is for ios only, I need one for Android platform

**Comment by ducpt2** [comment]
Does anyone working on this project? Thanks :)

**Comment by pgarciacamou** [comment]
@ducpt2 see https://github.com/pgarciacamou/react-native-opencv/issues/3

**Comment by mateusz-brainhub** [comment]
Here you can find a case study with an open source code on Github on how to do image processing with [OpenCV in React Native](https://brainhub.eu/blog/opencv-react-native-image-processing/)

Repo on [Github here](https://github.com/brainhubeu/react-native-opencv-tutorial)
